-- 코드를 작성해주세요
SELECT B.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_TREE A RIGHT OUTER JOIN ITEM_TREE B ON A.PARENT_ITEM_ID = B.ITEM_ID JOIN ITEM_INFO I ON B.ITEM_ID = I.ITEM_ID
WHERE A.ITEM_ID IS NULL
ORDER BY B.ITEM_ID DESC