-- 코드를 작성해주세요
WITH RECURSIVE GEN AS (
    SELECT ID, PARENT_ID, 1 AS G
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT A.ID, A.PARENT_ID, G + 1
    FROM ECOLI_DATA A JOIN GEN ON GEN.ID = A.PARENT_ID
)

SELECT COUNT(*) AS COUNT, G AS GENERATION
FROM GEN G LEFT OUTER JOIN ECOLI_DATA E ON G.ID = E.PARENT_ID
WHERE E.ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION ASC